# Generated by Django 3.2.4 on 2021-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('transmission', models.SmallIntegerField(choices=[(1, 'mechanics'), (2, 'automatic'), (3, 'robot')])),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
